### ISSUE TITLE
scala-mode dependency

### ISSUE THREAD

**Issue by sten0** [Fuco1/smartparens#1011]
Hi @Fuco1,

While packaging smartparens for Debian I discovered that self-tests require scala-mode.  Is this the https://github.com/hvesalai/emacs-scala-mode version?  Is there any reason why https://github.com/Fuco1/smartparens/blob/master/smartparens-scala.el doesn't declare a packages.el-style dependency on scala-mode?

Best,
Nicholas

**Comment by Fuco1** [comment]
It doesn't declare the dependency because it isn't a dependency: we don't want to pull 20 language modes for every user of SP (of which probably <1% uses scala).

Only if you already use scala mode then the config will register to be loaded after scala mode is active.

It is not a dependency of the package.  It is a dependency of tests because to test the config we need to have the environment.

I don't know if it's that package but it would be the one registered on melpa. Either way you probably should not package it.

**Comment by sten0** [comment]
Hi @Fuco1,

Thank you for your reply, and sorry for the delay in mine.  Ok, yeah, that makes sense.  That said, if a package is required for tests I'm required to package it, because failing tests = unfit for release in Debian :-)  eg: we need test coverage even for optional functionality.

The reason I asked about the source is because we have an obsolete scala-mode from a different upstream source that needs to be updated in Debian, so we might as well update it to use the same source as you--which appears to have become the canonical scala-mode on MELPA.

Thank you once again for confirming :-)
Regards,
Nicholas
