### ISSUE TITLE
org-mode: code marker should prevent nested pairs

### ISSUE THREAD

**Issue by asymmetric** [Fuco1/smartparens#1031]
## Expected behavior

`~0200::/|~` should stay how it is.

## Actual behavior

`~0200::/|/~`, i.e. a closing `/` is added, which doesn't make sense in org-mode, as it's not possible to italicize text within `~code markers~`.

## Environment & version information

- `smartparens` version: <Please specify manually>
- Active `major-mode`: `org-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10)
- Starterkit/Distribution: Doom
- OS: gnu/linux

**Comment by Fuco1** [comment]
Thanks, this is a good suggestion.  I added it to the default org config.

**Comment by jaccarmac** [comment]
The fix seems to cause massive input lag in a large Org file I have. I don't have minimal reproduction case yet, but there seems to be some interaction with single-quotes used as apostrophes in prose. It's not as simple as every such quote slowing down or speeding up text entry, but if I position my cursor after a certain quote near the end of the file, input is slow before said quote and normal afterwards. Calling `sp-backward-sexp` while positioned near a quote jumps to the preceding Org heading or, if there's an inline code block in the way, the beginning of that.

I may be doing something or have some garbage in the file to cause the pathological behavior, but since rolling back the single commit fixed things I'm dropping this note in under-debugged form.

**Comment by Fuco1** [comment]
That is very well possible.  I will try to add an optimization which is going to be usefull in general to limit "string" pairs to the current subtree, because they can't span out of a tree in org mode anyhow.  Might also want to stop the search on block boundaries and fixed width (line prefixed with `:`).

This is not exactly cause of your issue, but I believe it will fix it and make everything faster as well. I'll ping you when I have a fix if you would be willing to test it :)

I will track this in a new issue #1192
