### ISSUE TITLE
Way to wrap region and stay inside pairs

### ISSUE THREAD

**Issue by andreyorst** [Fuco1/smartparens#1051]
Sorry if this feature was asked or presented in Smartparens, I was unable to find it, and hack upon Smartparens to implement it myself. This is similar to https://github.com/Fuco1/smartparens/issues/508

# TL;DR

Provide a way to wrap region and stay inside pairs with point resting at beginning or end of region depending on what key is pressed without depending on region orientation. E.g.
```lisp
(|some text) ;; user selected "some text" and pressed "("
(some text|) ;; user selected "some text" and pressed ")"
[|some text] ;; user selected "some text" and pressed "["
[some text}] ;; user selected "some text" and pressed "]"
;; and so on
```

When writing in Lisp languages it is extremely useful, and Paredit does this for opening parenthesis, which I find very helpful.

## More detailed explanation
Currently it is possible to select a region and press <kbd>(</kbd> or <kbd>)</kbd> and have this outcome:

(`%` represents region, `|` represents point)
Region:
```
%some text|
```
press <kbd>(</kbd>:
```
(some text)|
```
It works the same with <kbd>)</kbd>
Region:
```
%some text|
```
press <kbd>)</kbd>:
```
(some text)|
```

If we reverse region, we get the desired outcome when pressing <kbd>(</kbd>.
Region:
```
|some text%
```
press <kbd>(</kbd>:
```
(|some text)
```
But if we press <kbd>)</kbd> we are out of the pairs again:
Region:
```
|some text%
```
press <kbd>)</kbd>:
```
(some text)|
```

There also is a variable `sp-wrap-respect-direction`, which I can set to true, and this will work mostly like I want it to without manually reversing region, however it keeps the point outside of the parentheses:

Region:
```
%some text|
```
press <kbd>(</kbd>:
```
|(some text)
```
It works the same with <kbd>)</kbd>
Region:
```
%some text|
```
press <kbd>)</kbd>:
```
(some text)|
```

**Comment by andreyorst** [comment]
A possible solution was suggested in Emacs chat in telegram:

```emacs-lisp
(setq sp-wrap-respect-direction t)

(defun sp--wrap-fix-cursor-position (_id action _context)
  (when (and (eq action 'wrap)
             (eq (point)
                 ;; position before delimiter
                 (marker-position (sp-get sp-last-wrapped-region :beg))))
    (goto-char
     ;; position after delimiter
     (sp-get sp-last-wrapped-region :beg-in))))

(sp-pair "(" nil :post-handlers '(:add sp--wrap-fix-cursor-position))
```

This makes <kbd>(</kbd> behave like in Paredit.

**Comment by Fuco1** [comment]
So to summarize, you want the exact same behaviour as we get when `sp-wrap-respect-direction` and additional *always* (or only in some cases?) to position the cursor inside the pair.  Is this correct?

**Comment by andreyorst** [comment]
Yes, I want a toggle tat will make it possible to define this behavior for all pairs. Like sp-wrap-respect-direction, makes smartparens respect direction, I want a way of being able to stay inside or outside by toggling some variable.

**Comment by andreyorst** [comment]
Answering your question: yes, always

**Comment by Fuco1** [comment]
What you say makes sense and in org mode I also often fight the same issue (note that you can `sp-down-sexp` to jump in the `=asd=` pair).

I think I would like this with the string-like delimiters, but for code I'm not so sure.  I don't consciously remember this ever annoying me too much.  Since a per-pair setting is already mentioned in your answer, adding a global setting might make sense).

I think instead of adding more settings I will extend `sp--run-hook-with-args` (which fires the events based on the pair) to also fire a global hook.  This way you can add your function from above to this hook and it will always trigger.

Overall I'm quite happy that even after 8 years the extension API/configuration is still capable of solving almost any issue... but it is clunky as hell, especially for newcomers.  Bad thing is I don't quite have ideas how to make it nicer and also backward compatible.
