### ISSUE TITLE
Typing ":" does not skip over colon auto-inserted by smartparens

### ISSUE THREAD

**Issue by marienz** [Fuco1/smartparens#1075]
## Expected behavior
Smartparens skips over the colon it automatically inserted after a Python function definition (after #1063) if I unnecessarily type that colon manually, just like it does with auto-inserted closing parens.

## Actual behavior
An extra colon is left after point which I have to manually delete.

## Steps to reproduce the problem
In a python-mode buffer with smartparens enabled in its default configuration, type `def f():` (typing both the closing paren and colon) and press RET. Point is now on the line after the function definition with a stray colon after it, which stays if I write more code.

## Environment & version information
- `smartparens` version: 20201229.1937
- Active `major-mode`: `python-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 27.1 (build 1, x86_64-redhat-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars) of 2020-08-21
- Starterkit/Distribution: Vanilla
- OS: gnu/linux

(I'm also seeing this in Spacemacs, but I reproduced it in vanilla with no customizations to make sure it's not Spacemacs weirdness).

This might be me using smartparens wrong, but I only really use its auto-inserted parens when editing code (adding a single parenthesized expression), where it lets me stop editing without having to type the closing parens. When I'm writing more than one line of code or pair of parens, I just type the closing parens instead of moving point past them. Smartparens normally supports this: I'm not really benefiting from the auto-inserted parens but they don't negatively affect me either. This auto-inserted colon is different, and seems to require that I change how I write code.

I'm honestly not sure if skipping past all colons would work, or if it'd have to treat the one after a function definition differently to not get in the way... I don't think typing a colon while another colon is after point is common, but I'm not sure it'll never happen.

**Comment by Fuco1** [comment]
Unfortunately, this is not possible to implement.  The inserted colon is added during a "post insert" hook in a special python handler.  There is no mechanisms to skip such additional content.  The reason is mostly that your additional `:` insertion is not "managed" by smartparens anymore, and so we would have no context etc.  Of course, everything is solvable, but this might just be too much effort.

There is probably a setting you can toggle to disable the behaviour altogether.

**Comment by Fuco1** [comment]
Yes, changing `sp-python-insert-colon-in-function-definitions` to `nil` would disable the insertion of `:`.  I think this is the simplest solution for your workflow.  We might want to change the default to `nil` later if it will be too confusing for existing users.

**Comment by marienz** [comment]
Makes sense, thanks for considering!

My 2 cents: this colon auto-insert feels odd, not just because of having to change how I write function definitions, but also because the colon in a function definition doesn't feel special enough to be the only one getting this treatment. These two issues compound: it's not just that it changes my workflow, it only changes in one situation that I previously didn't have to consider separately.

The colons at end of line after `class`, `def`, and `if` in this snippet are all equally mandatory:

```python
class Number:
    pass

class AddableNumber(Number):
    def add(self, other: int) -> int:
        if self.bad_at_math:
            return 42
        return self.value + other
```

Especially `class` statements are similar enough to `def` statements that it feels odd to me they don't get auto-inserted colons too.

But it actually feels a bit odd to me that the colon in other compound statements (like `if`, or `class` statements that don't specify a base class) isn't auto-inserted either... except those would have to auto-insert after the keyword, as there is no paren to tie the auto-insert to.

So how I'd expect a feature like this to work is that it auto-inserts a colon on pressing space after any keyword that starts a compound statement that must end in one (the keyword and the colon form a pair somewhat similarly to how an opening and closing paren form one). This would include inserting the colon after typing `def`, before typing the opening paren. But autoinsert on space might be too odd a feature to put in smartparens (especially because `if` as part of a ternary expression like `foo(x) if x is not None else some_default` shouldn't trigger a colon, while `def` as part of `async def f():` should... the amount of context to consider gets out of hand).

(And to be honest I'd probably still disable this if it doesn't skip over the colon if I type it, which gets us back to that probably being _way_ too out there a feature for smartparens to implement.)

(Also, smartparens currently doesn't auto-insert the colon in `async def f():`, but that looks like more of an easily fixable bug in the current feature than anything systemic. `async` is the only thing that can currently occur on the same line before `def`, so the regular expression approach in `sp-python-maybe-add-colon-python` could support it.)

**Comment by Fuco1** [comment]
@Hi-Angel What do you think about this?  Would it be difficult to improve with the current approach, or should we disable by default?

I'm not a huge python user so I don't/shouldn't form an opinion on this.

Thanks for the feedback @marienz.

**Comment by Hi-Angel** [comment]
Hi all, thanks for mentioning possible issues!

So, I'll try to reply main points I see, please tell if I miss something.

> Also, smartparens currently doesn't auto-insert the colon in `async def f():`, but that looks like more of an easily fixable bug in the current feature than anything systemic.

Sure, sounds easy, I can send a PR.

> So how I'd expect a feature like this to work is that it auto-inserts a colon on pressing space after any keyword that starts a compound statement that must end in one

Sounds possible to implement *(I think, adding a callback to `post-self-insert-hook`)*; however, since there's no parens to hook up to, I think that would be a feature that isn't using smartparens in any way.

> But it actually feels a bit odd to me that the colon in other compound statements (like `if`, or `class` statements that don't specify a base class) isn't auto-inserted either... except those would have to auto-insert after the keyword, as there is no paren to tie the auto-insert to.
> […]
> […] But autoinsert on space might be too odd a feature to put in smartparens (especially because if as part of a ternary expression like `foo(x) if x is not None else some_default` shouldn't trigger a colon, while `def` as part of `async def f():` should... the amount of context to consider gets out of hand).

I agree. It is sure a general rule that the more things are automated the better, because it makes a person less to type.

The problem with more automation though was also mentioned in the quote, but I'd like to focus on it: the more automation requires more code. For example, pre-detecting a ternary-if requires a full-blown parser. I can think of a python code where the ternary starts on a newline, so it may look like an alone `if` till you look at the previous line and find a backslash; and then there probably may be other corner-cases…

So, what we can do as programmers is to try to automate what's possible within our lifetime and with other things in life considered.

When I automated colon autoinsertion, main reasons I did it were: it α) was easily achievable and β) isn't prone to errors *(because function context in python is unambiguous)*, γ) it bugged me. Reason I didn't do that for `class` is trivial: I just didn't happen to work with inheritance in python often enough to care. *(to elaborate, I code in lots of different languages both in and out of work; and the place where I happened to use Python last year was mainly refactoring some utilities and unit-testing at dayjob. Python inheritance I happened to exploit just once to deduplicate some code)*

With that said, I'm glad to help Emacs and Linux users, so I might implement colon-autoinsertion for `class` as well if there is interest from anyone. Sounds easy, and the context should be unambiguous as well.

> @Hi-Angel What do you think about this? Would it be difficult to improve with the current approach

In the discussion so far were multiple ideas mentioned, so I'm not sure what exactly implies "improve". I can add a rule for `class` and `async def` if that's being implied.

> , or should we disable by default?

Well, you're the maintainer, but if you ask my opinion, I think that "some automation" is better than "no automation".

The question of defaults is, I think, whether there're more people who will want this automation or those who won't. Apparently, I am not competent enough to answer that question, because till now I was 100% sure that feature won't hurt anyone's workflow.

Now that I think of that, conceptually a colon in a function definition context should define a pair, but we can not treat it properly so *(as was mentioned in the 2nd comment here)*. So, I can kinda see where the question in the issue is coming from.

**Comment by marienz** [comment]
Good point about multi-line ternary. I normally keep ternaries small enough it's not needed, but I'm sure there's code out there splitting `value` / `if cond` / `else other_value` over three lines (as part of a list comprehension or the like).

I'm on the fence about the default myself now. The option to disable this if you don't like it isn't that hard to find, but if it's disabled by default it's less likely someone who'd benefit from this feature would figure out it exists. So maybe leaving it enabled just for discoverability is the right choice.

**Comment by mfdorst** [comment]
I for one am firmly in the camp that this should be **disabled by default**. Compare these two workflows:
+ **No automatic semicolon:**
    User types `def func(p1, p2, p3):` and then presses `<return>`.
+ **With automatic semicolon:**
    User types `def func(p1, p2, p3` and then presses `ESC o`.

The automatic semicolon only saves a single keystroke, and it does it at the expense of intuition. It requires the programmer to remember not to type `):` as they are used to doing in every other program, and penalizes them every time they forget by requiring them to type `ESC l x i` to get rid of the extra colon and get back to insert mode.

I think that the ideal scenario is to have the semicolon "skipped over" when typed the way that the closing parenthesis is. If this is not possible to do (as was stated above), then the next best thing is to disable this feature by default and let people type their own semicolons.

**Comment by Hi-Angel** [comment]
I have no strong opinion for reasons described at the end of my last comment, so on my side I leave decision to the maintainer.

**Comment by dakra** [comment]
After not writing much Python in the last year I finally got around to find out what's inserting the `:` after a Python def.
I have it disabled now, so all good, but like @mfdorst, I'm also firmly in the camp that this should be disabled by default.

I don't even see the point really as it doesn't really save you any keystrokes and it's just confusing.
So often I type `def foo(arg1): <enter>` and end up with
```
def foo(arg1):
    :
```

**Comment by Fuco1** [comment]
I've been writing a lot of python recently and never even noticed the behaviour, it just worked for me fine.  The moment pair is inserted I just go to next line.  I think my mental model changed to just never type the closing paren and that means I will never reach the colon either.  

I added the class and async support and I think I will keep this on by default.  There is an option to disable it.

**Comment by Fuco1** [comment]
I use this function from my config, bound to `C-o`

```elisp
(defun my-open-line (&optional arg)
  "If point is before the beginning of \"code\", open new line,
keep the cursor at the current line and autoindent.

If point is in the middle of the line, create a blank line under
current line, move cursor to this new line and autoindent.

With raw prefix \\[universal-argument] insert newline at point
and indent next line according to mode."
  (interactive "P")
  (if (or (<= (point) (save-excursion
                        (my--back-to-indentation)
                        (point)))
          (equal arg '(4)))
      (progn
        (save-excursion
          (my-newline (if (equal arg '(4)) 1 arg)))
        (indent-according-to-mode))
    (end-of-line)
    (open-line (prefix-numeric-value arg))
    (forward-line 1)
    (insert (fill-context-prefix (point-at-bol) (point-at-eol)))
    (indent-according-to-mode)))
```

But I think I'm going to reconsider and disable this by default, since it is not obvious how to avoid some extra steps if not specifically baked into the workflow.

**Comment by doolio** [comment]
OK thanks.

**Comment by Hi-Angel** [comment]
FTR, in Evil mode there's by default an analog of the `my-open-line` — simply pressing <kbd>o</kbd> in normal mode. Before I started using Evil I also had a similar custom function.

But yeah, I agree it's something to be baked into the workflow.
