### ISSUE TITLE
Quote and backquote pair is inserted in Lisp Interaction mode with strict mode

### ISSUE THREAD

**Issue by veronikazaglotova** [Fuco1/smartparens#1080]
## Expected behavior

Typing \` or ' will insert one \` or '

## Actual behavior

Typing \` or ' inserts \`\` and ''

## Steps to reproduce the problem

1. Start Emacs
2. Switch to \*scratch\* buffer
3. Enable smartparens-strict-mode
4. Type a backquote (\`) or a quote (')

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: 20210213.1851
- Active `major-mode`: `lisp-interaction-mode`
- Smartparens strict mode: t
- Emacs version (`M-x emacs-version`): GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-29
- Starterkit/Distribution: Vanilla
- OS: gnu/linux

**Comment by veronikazaglotova** [comment]
Yes, I tested that with -Q and the bug was there

**Comment by andreyorst** [comment]
Have you required `smartparens-config` module?

``` emacs-lisp
(require 'smartparens-config)
```

**Comment by veronikazaglotova** [comment]
I'm sorry for bothering you...

**Comment by Fuco1** [comment]
Hi Veronika, no worries!  I take it your problem was solved?

I personally find the `smartparens-config` thing confusing, but in the past a lot of people were angry about the defaults "being forced on them".  With Emacs it's really hard to "unload" settings, so an opt-out strategy isn't/wasn't really possible.  

Considering it's 2021 and a lot of things changed since 2012, maybe loading this eagerly could be the new default and some code wrapping the entire module with a `defcustom` check could be a solution for an opt-out.
