### ISSUE TITLE
Install error: Wrong type argument: integer-or-marker-p

### ISSUE THREAD

**Issue by ekenberg** [Fuco1/smartparens#241]
I'm trying to install smartparens from MELPA:

Compiling file /home/johan/.emacs.d/elpa/smartparens-20131123.2120/smartparens.el at Sun Nov 24 01:33:35 2013
smartparens.el:1647:1:Error: Wrong type argument: integer-or-marker-p, (or wrap bind)

Emacs version 24.2.1

**Comment by Fuco1** [comment]
Does this still happen to you on 24.4? If yes, we'll need to do something with it.

(I'm getting back into fixing up the backlog :)

**Comment by Wilfred** [comment]
@Fuco1 do we still support Emacs 24.2?

**Comment by Fuco1** [comment]
I would like to have support for all 24.*

I don't think this issue is worth spending time on though.  (I'm not sure the code causing this is even in place, maybe we should at least try to reproduce this).

Also, an idea... we could add a byte-compile/package build step to travis CI so we see where and if and how it breaks.  The tests run for 24.3+ at the moment because I couldn't figure out how to add optional dependency for racket-mode (which requires 24.3+)
