### ISSUE TITLE
Suggesting a pair for haskell-mode

### ISSUE THREAD

**Issue by MichaelXavier** [Fuco1/smartparens#424]
For a long time I had an issue with smartparens where if my point was on a LANGUAGE pragma, the minibuffer would constantly have the following error "Search failed. This means there is unmatched expression somewhere or we are at the beginning/end of file".

You can reproduce this by opening a buffer in Haskell mode and start it like this:

```haskell
{-# LANGUAGE OverloadedStrings #-}
```

The thing that fixed it was:

```elisp
(sp-local-pair 'haskell-mode "{-#" "#-}")
```

I advocate adding this to smartparens itself so haskell developers don't have to see this weird error message and research to come to the same conclusion. I presume that this would not have any negative impact for users who don't use haskell as it would never get activated.

Thanks

**Comment by vikraman** [comment]
This is also required for `agda2-mode`.

**Comment by Fuco1** [comment]
I'm happy to take a patch :) All that is required is to

* put specific haskell config in `smartparens-haskell.el`
* setup auto include in `smartparens-config.el`

If haskell mode and agda mode share a lot of configuration, maybe we should put it in one common file.

Note that on master, insertion of tags with shared prefixes now works without any issues, so you can just type `{-` and it inserts `{--}` instead of (old behaviour) `{-}`.

**Comment by MichaelXavier** [comment]
Cool. I'll try to get you a patch sometime this week, hopefully soon.
