### ISSUE TITLE
Recent smartparens breaks Yasnippet expansion

### ISSUE THREAD

**Issue by YorkZ** [Fuco1/smartparens#431]
The following is my snippet:

    # -*- mode: snippet -*-
    # name: forr
    # key: forr
    # --
    for (${1:i = 0}; ${2:i < N}; ${3:i++}) {
      $0
    }

In a C++ buffer, when typing "forr", it expands to the following:

    for (|)i = 0; i < N; i++) {

    }

`|' is the position of the point after expanding the snippet. Hitting TAB wouldn't goto the next field.

The problem won't show up if I either turn off `auto-complete`, or turn off `smartparens`. Therefore, this might not be a problem of `smartparens`. If that's the case, my apology.

This problem is really painful, and I would appreciate any help.

Thanks

**Comment by expez** [comment]
There's a `yas-{before,after}-snippet-hook` that you can use to toggle smartparens or auto-complete-mode while inside the snippet.

I'm not sure it's in smartparens best interest to try to maintain compatibility layers with every other package out there.

**Comment by tuhdo** [comment]
Not every other but popular packages. Otherwise users will be forced to choose one.  Maybe a documentation update would be enough to note this issue for Yasnippet users with some workaround:

```elisp
(add-hook 'yas-before-expand-snippet-hook (lambda () (smartparens-mode -1)))
(add-hook 'yas-after-exit-snippet-hook (lambda () (smartparens-mode 1)))
```

**Comment by expez** [comment]
Since this only appears in combination with `auto-complete` I don't want to do anything about this.  I consider `auto-complete` to be deprecated and everyone should migrate to the far less buggy and more user-friendly `company-mode`.

**Comment by YorkZ** [comment]
After some investigation, I've figured out that it was commit "abe7b12", subject "Improve sp-region-ok-p", that has introduced the issue. Sorry I should have figured out this earlier, but I was crazily busy recently and didn't have any time.

I would appreciate it if the issue can be addressed. Also, I don't think switching to company-mode is always an easy decision for everybody, especially if his system has been heavily customized with auto-complete-mode.

**Comment by expez** [comment]
@YorkZ thanks for taking a closer look.  `sp-region-ok` is only used in one place, in `sp-newline`.  I've been making changes to `sp-region-ok-p` (it was super broken in general, but seems to have done what it should when used in the context of `sp-newline`), because I want to use it as the basis for region manipulations in `evil-smartparens`.

If you leave out the `""` quotes, github will create a nice link to the commit, btw.   abe7b12 is quite old and it is indeed likely that it introduced a regression in the capabilities of `sp-region-ok-p`.  I've made several commits since, improving this function.  Would you mind pulling in the latest version of smartparens to see if that solves your problem?

**Comment by YorkZ** [comment]
@expez: thanks for the quick responding, and thank you for the reminder of removing double quotation surrounding a commit number, I've changed that.

I always use the latest commit, that said, the issue is still there. I'm now using the commit right before abe7b12, and Yasnippet works like a charm again. I really hope this issue can be addressed so that I will be able to come back to the latest.

**Comment by expez** [comment]
I cannot reproduce this.  I've copied your snippet (I'm not using auto-complete, but you said that was unrelated) and am testing it in cpp mode with smartparens enabled.

This example from your first post:
```
for (|)i = 0; i < N; i++) {

}
```

indicates that there's some problem with the initial snippet insertion. Notice how your point is between parens, but it should be next to an opening paren only.  Perhaps some other parens-inserting-mode is creating problems? `electric-pair-mode` perhaps?

Furthermore, the fact that `sp-newline` is involved (as that is the only function which uses `sp-region-ok-p` seems so unlikely, because in the steps to reproduce the issue no newlines are involved, only `TAB`.

Also, the snippet you've provided does not expand in the manner you've described.  The snippet ends with `{ $0 }`, which has no newlines,  yet your expansion is: 

```
<start of snippet> { 

}
```

If you're actually seeing the newlines then part of your emacs configuration is doing that too.  I know that `electric-pair-mode` does stuff like that for me when I'm writing javascript or css.

Until you can help me reproduce the problem, starting from `emacs -Q` preferably, it's impossible to know what went wrong.  If you have a large emacs configuration tons of stuff could be interfering.  If you cannot reproduce it from `emacs -Q` then the only thing to do is to start bisecting your emacs configuration to find out exactly where the conflict lies.

**Comment by YorkZ** [comment]
First of all, I apologize for my late responding.

> I'm not using auto-complete, but you said that was unrelated.

I don't think I've ever said they were unrelated. Instead, they are closely related. Please take a look at [my comment in the related auto-complete issue]( https://github.com/auto-complete/auto-complete/issues/379#issuecomment-72143616). Anyway, you have to turn on both `auto-complete-mode` and `smartparens-mode` to reproduce this issue.

> Perhaps some other parens-inserting-mode is creating problems? electric-pair-mode perhaps?

I don't think I'm using `electric-pair-mode`, and I just double checked with "C-h v electric-pair-mode" in a C++ buffer, the value is `nil`.

> Also, the snippet you've provided does not expand in the manner you've described. The snippet ends with { $0 }, which has no newlines

> If you're actually seeing the newlines then part of your emacs configuration is doing that too. I know that electric-pair-mode does stuff like that for me when I'm writing javascript or css.

My snippet does have newlines surrounding the `$0`, like below:

    for (${1:i = 0}; ${2:i < N}; ${3:i++}) {
      $0
    }

I apologize for this. It was my mistake because I composed my GitHub comment in Emacs. However, before pasting into GitHub, I normally do "unfill" to turn the 80 characters lines into long lines. It was this "unfill" that removed the newlines around the `$0`. I've corrected this in my first post.

> Until you can help me reproduce the problem, starting from emacs -Q preferably, it's impossible to know what went wrong.

I'm not sure if I still have to start from `emacs -Q` because I've already tracked down the issue to `auto-complete-mode` and `smartparens-mode`, and further, the commit abe7b12. I hope you can turn on `auto-complete-mode`, just to produces the issue though.

Also, I just noticed [this comment ](https://github.com/auto-complete/auto-complete/issues/379#issuecomment-74373540), and [this comment](https://github.com/auto-complete/auto-complete/issues/379#issuecomment-74373652), in the related `auto-complete` issue. Looks promising, and I will give it a try.

Thank you very much for your help.

**Comment by YorkZ** [comment]
Hi Lars,

Please check out the recent comments in the related `auto-complete` issue I mentioned in my previous comment. As soon as I removed the `ac-complete advice` in `smartparens.el`, the original problem went away.

Therefore, would you consider removing this advice if it's not needed?

Thanks,
York

**Comment by expez** [comment]
Thanks for getting to the bottom of this, @YorkZ!
