### ISSUE TITLE
sp-insert-pair: wrong-type-argument char-or-string-p nil

### ISSUE THREAD

**Issue by jorgenschaefer** [Fuco1/smartparens#439]
Running smartparens 1.6.3, entering a " in some particular place in a (longish) org-mode document results in this error:

```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  sp-insert-pair()
  ad-Advice-self-insert-command(#<subr self-insert-command> 1)
  apply(ad-Advice-self-insert-command #<subr self-insert-command> 1)
  self-insert-command(1)
  sp--self-insert-command(1)
  funcall-interactively(sp--self-insert-command 1)
  call-interactively(sp--self-insert-command nil nil)
  command-execute(sp--self-insert-command)
```

I can't find a small reproduction case and can not publish the org file, sorry.

**Comment by Fuco1** [comment]
What emacs version is this? I've never seen the `#<subr self-insert-command>` output before.

I'm still at 24.3 because I feer breakage and I don't have time to fix all my config :/

I seem to recall this issue, I'll dig around a bit.

Sigh... I tried adding tests for 24.4 but the downloader was broken so I removed it again.  I need to get that working again. I don't understand the travis setup at all :D

**Comment by jorgenschaefer** [comment]
This was on the Emacs master branch (25.0.50) from sometime in October last year.

EVM now supports 24.4, by the way. You can look at [Elpy's .travis.yml](https://github.com/jorgenschaefer/elpy/blob/master/.travis.yml) for a working version.

**Comment by Fuco1** [comment]
The advice is now removed in the new stable version (1.7.*) so this is no longer a problem.  It caused a lot of similar problems so it had to go.
