### ISSUE TITLE
sp-forward-slurp-sexp adds weird newlines in C++

### ISSUE THREAD

**Issue by pronobis** [Fuco1/smartparens#444]
For the following situation:
```
if (a)
{
| }

int b;
```

running `sp-forward-slurp-sexp` results in:

```
if (a)
{
 

  in
      t} b;
```

While it should be:
```
if (a)
{
 

  int} b;
```

**Comment by Fuco1** [comment]
What language? It is most likely that `in` is a keyword and SP treats it as such.

**Comment by pronobis** [comment]
It's  c++.

**Comment by pronobis** [comment]
Shouldn't it just move over sexps in such situation?

**Comment by Fuco1** [comment]
Well, in really old SP there was a bug when having a word containing a keyword would get split, so `ending` in ruby would be interpreted as closing-paren-token `end` and some token `ing`.

Maybe you have some setting making `in` a token SP recognizes.

When I try your example, I get the usual expected behaviour.

**Comment by pronobis** [comment]
I run edebug and got to the line 
`(sp--run-hook-with-args (sp-get enc :op) :pre-handlers 'slurp-forward)`
which causes the line break. What's the best way to debug that?

**Comment by Fuco1** [comment]
You can use `(sp-get-pair "{")` in that buffer to get all the information about `{` pair.  Look for the handlers/hooks

**Comment by Wilfred** [comment]
I can no longer reproduce this, the expected behaviour described is occurring. Hooray!
