### ISSUE TITLE
Further tweaks to Haskell mode

### ISSUE THREAD

**Issue by rpglover64** [Fuco1/smartparens#465]
* `'` should not be matched; it is an identifier character, not a string delimiter
* `\(` should be matched by `)`; the backslash indicates an anonymous function, not an escape

**Comment by Fuco1** [comment]
`'` can mean a character in which case it should be paired.  I use `(sp-local-pair 'haskell-mode "'" nil :unless '(my-after-symbol-p))` in my config

The issue with `\(` should be fixed by specifying contexts where `\(` should pair, if ever.  The pair could probably just be removed entirely.  That is what I do `(sp-local-pair 'haskell-mode "\\(" nil :actions nil)`

We could probably add

```elisp
(sp-with-modes '(haskell-mode)
  (sp-local-pair "'" nil :unless '(my-after-symbol-p))
  (sp-local-pair "\\(" nil :actions nil))
```

to the haskell config file.

**Comment by rpglover64** [comment]
I tried `(sp-local-pair 'haskell-mode "\\(" nil :actions nil)`, but that seemed to break my normal parentheses matching. That could have been noise due to the other stuff I was modifying, though.

It's been a _loooong_ time since I've used characters in Haskell (I don't write many parsers), so I forgot.

**Comment by unhammer** [comment]
I use ` (sp-local-pair 'haskell-mode "\\(" nil :actions nil)` without normal parens matching broken, seems to work a lot better with that than without.
