### ISSUE TITLE
Setting a post-handler not working in coffee-mode 

### ISSUE THREAD

**Issue by jasoncyu** [Fuco1/smartparens#472]
```lisp
  (sp-local-pair 'coffee-mode "{" nil :post-handlers '((my-create-newline-and-enter-sexp "RET")))

  (defun my-create-newline-and-enter-sexp (&rest _ignored)
    (message "called")
    (newline)
    (newline)
    (forward-line -1)
    (coffee-indent-line)
    )
```

After running the following code, after I type a "{" in coffee-mode and press return immediately, nothing happens. But if I instead use the letter "a'" instead of "RET", then `my-create-newline-and-enter-sexp` is executed.

I suspect this is because `RET` is already bound to `coffee-newline-and-indent` in evil-insert mode. What's a good solution to this without unbinding `RET` from `coffee-newline-and-indent` outright?

**Comment by Fuco1** [comment]
You can also use the name of the command (as a symbol) instead of the keyboard action, which is indeed "messed up" by evil.  If evil respects the `last-command` variable it will work fine.

**Comment by Fuco1** [comment]
Quoting the documentation

> A special syntax for conditional execution of hooks is also
supported.  If the added item is a list (function command1
command2...), where funciton is a 3 argument function described
above and command(s) can be either name of a command or a string
representing an event.  If the last command the event as
described by `single-key-description' matches any on the list,
the hook will be executed.  This means these hooks are run not
after the insertion, but after the *next* command is executed.

> Example:
```elisp
  ((lambda (id act con)
     (save-excursion
       (newline))) \"RET\" newline)
```

> This function will move the closing pair on its own line only if
the next command is `newline' or is triggered by RET.  Otherwise
the pairs stay on the same line.
