### ISSUE TITLE
Add customize option to *not* indent region after e.g. slurping in certain modes

### ISSUE THREAD

**Issue by rpglover64** [Fuco1/smartparens#493]
Certain modes have a broken `indent-region` (c.f. haskell/haskell-mode#796), and smartparens would be more useful it it didn't try to reindent after modifying the document in these cases.

**Comment by Fuco1** [comment]
See this: https://github.com/Fuco1/smartparens/pull/403

Maybe we should extend that setting to all the "post-command automatic attempts to fix indent".

If someone cares to take it up, I wouldn't mind.  This is a low priority task for me right now, unfortunatelly I barely have time to work on the "important" issues anymore :/

**Comment by rpglover64** [comment]
I noticed that and started hacking something up, but I wasn't sure which commands to do reindent for and which ones not to.

**Comment by Fuco1** [comment]
Well, if the indent breaks thing then I guess it makes sense to either have it or not at all.

But I think a better approach would be not to call reindents at all from the body directly but add it as a hook action.  Then users can add or remove the hook as they like... and we can remove it in the `smartparens-foo.el` config files for the languages where it makes no sense by default.  Most interactive functions should raise an event which can be catched with the pre/post handlers, and if they don't that functionality should be added. (see `sp--run-hook-with-args` in various commands).

Because this global approach is not going to give us too much control.  It's probably a good temporary solution though.

**Comment by Fuco1** [comment]
This is handled in #494 and #513

**Comment by rpglover64** [comment]
It's not fully solved yet... for example, slurping and barfing still cause the indentation issue.
