### ISSUE TITLE
Rewrap-sexp minibuffer impossible to get out of

### ISSUE THREAD

**Issue by endrebak** [Fuco1/smartparens#535]
I have the problem that when I want to rewrap a sexp with anything but the common `"[{(` I get a prompt it is impossible to get out of.

![screenshot 2015-11-16 20 06 42](https://cloud.githubusercontent.com/assets/5526486/11191800/ace81d46-8c9d-11e5-87bf-f7935338c210.png)

You can see above that I tried to wrap the sexp with `'` and it did not work.

**Comment by Fuco1** [comment]
`C-g` should help.  But that interface is quite bad and we should come up with something better.

**Comment by endrebak** [comment]
A simple fix for a large subset of cases would be to have a one-letter version of `wrap-sexp` which only lets you use one letter. My naive guess would be that most users would want this most of the time.

I only want to wrap with one letter so if a paired letter is entered wrap with that pair, if a non-paired letter is entered just insert two of it: 

Examples of of non-paired:
```
\`/'x 
```

This is a chance to improve the function for 99% of use-cases. 

Thanks for the package by the way.

**Comment by Fuco1** [comment]
I sometimes use it in latex to swap `$` and `\(` or `\[` which all denote math mode, so two-char pairs can in some situations be useful too.

I think I'll do it like this: read the characters as it does now, but if an impossible combination is inserted abort or restart.  Detecting an impossible combination is as simple as comparing whatever you inserted with all the available pairs as a prefix.

Btw your example came out weird, probably because of escaping.  I'm not sure what it tries to illustrate.

And thanks :)
