### ISSUE TITLE
please don't bind C-<left, right>

### ISSUE THREAD

**Issue by fommil** [Fuco1/smartparens#543]
I do this after loading the default bindings

``` elisp
  (bind-key "C-<left>" nil smartparens-mode-map)
  (bind-key "C-<right>" nil smartparens-mode-map)
```

and I think it catches out many people who I introduce to smart-parens. These key bindings are a little too popular for other purposes to be rebound the way you're doing, IMHO.

**Comment by Fuco1** [comment]
I'm not binding anything, you have to enable it in customization.  If you enable them, the bindings follow paredit.

Smartparents supports customizable "keybinding sets", if you think there is some which would be better for beginners, I'm happy to add third type.

See the variable `sp-base-key-bindings`.

**Comment by fommil** [comment]
I mean specifically in the default call to `(sp-use-smartparens-bindings)`

**Comment by Fuco1** [comment]
Okey, I still think it would be better to add another set or customization option.  If only with respect to compatibility and my own selfish lazyness.

For the paredit users there's the paredit set, for users who want something like paredit but not quite (e.g. never used paredit so they don't care) there is the smartparents set which is basically what I use (with some changes wrt paredit which I didn't quite like).  I don't know what `C-<left>` should do otherwise, so I can't argue about that with you.  But I see no problem with some "CUA" set or whatever we want to call it.

**Comment by fommil** [comment]
yeah, that'd be great! And since its the one that newbies will likely see, can it be the default? :-D

FYI, these are the bindings I use

```elisp
  (bind-key "s-<delete>" 'sp-kill-sexp smartparens-mode-map)
  (bind-key "s-<backspace>" 'sp-backward-kill-sexp smartparens-mode-map)
  (bind-key "s-<home>" 'sp-beginning-of-sexp smartparens-mode-map)
  (bind-key "s-<end>" 'sp-end-of-sexp smartparens-mode-map)
  (bind-key "s-<up>" 'sp-beginning-of-previous-sexp smartparens-mode-map)
  ;; sp-next-sp could be better https://github.com/Fuco1/smartparens/issues/541
  (bind-key "s-<down>" 'sp-next-sexp smartparens-mode-map)
  (bind-key "s-<left>" 'sp-backward-up-sexp smartparens-mode-map)
  (bind-key "s-<right>" 'sp-down-sexp smartparens-mode-map)
```

**Comment by fommil** [comment]
did you ever do anything on this? I've added a recommendation section to the ensime docs telling people to install smartparens :smile: http://ensime.github.io//editors/emacs/hacks/#smart-parentheses

**Comment by Fuco1** [comment]
Hi.  Are you still interested in this?

**Comment by fommil** [comment]
yup, it would be great to remove these from the default binding.
