### ISSUE TITLE
Curious handling of punctuation in slurp/barf

### ISSUE THREAD

**Issue by Skinney** [Fuco1/smartparens#577]
I have the following code

``` js
someFunc("name", getProp(this), 23, "21st street");
```

If I have my cursor on `this` and barf to the right, I get the following:

``` js
someFunc("name", getProp(this, 23,) "21st street");
```

You will see the comma is included when expanding the parens. I would expect the paren to end just before the comma.

**Comment by Fuco1** [comment]
I get this instead

```js
someFunc("name", getProp(this 23,), "21st street");
```

There is some setting for this already, try searching through the issues.  I think someone wanted to write js support but seems like they haven't yet.  I don't do js so this is not very high priority now unfortunatelly.

**Comment by Wasabichicken** [comment]
It seems relevant for several C-like languages (including C, C++, Java etc) and not only Javascript. For those languages I understand we are to use `sp-slurp-hybrid-sexp` instead, but then I end up with this:

```javascript
someFunc("name", getProp(this 23),, "21st street");
```

**Comment by Fuco1** [comment]
It's not perfect, I agree.

I have thought quite a bit about the handling of punctuation, and the problem is that it isn't always obvious what to do... sometimes you need to move it with the delimiter and sometimes not, sometimes you want to skip... it all depends on the syntax of the given language.

Without some more precise info it is always only guessing and heuristics, and they aren't stellar.

**Comment by chessman** [comment]
I use the same settings in javascript as in scala (https://github.com/Fuco1/smartparens/blob/master/smartparens-scala.el):

``` lisp
(add-to-list 'sp-sexp-suffix (list 'js2-mode 'regexp ""))
```
`sp-slurp-hybrid-sexp` works as expected.
