### ISSUE TITLE
sp-up-sexp with sp-navigate-reindent-after-up doesn't work

### ISSUE THREAD

**Issue by cpmcdaniel** [Fuco1/smartparens#599]
According to the docs for `sp-up-sexp` and it's interaction with `sp-navigate-reindent-after-up`, the following should work:

```
(foo bar |baz              -> (foo bar baz)| ;; re-indent the expression
​   )
```

I have bound ')' to `sp-up-exp`, so I figured the problem was that the modes in `sp-navigate-reindent-after-up` are wrapped in `interactive`, so I configured the following:

```
(setq-default sp-navigate-reindent-after-up
                `((always ,@sp-lisp-modes)))
```

...but it still doesn't work. Is this a bug or just a misunderstanding of the documentation?

**Comment by cpmcdaniel** [comment]
Perhaps I'm looking at the wrong feature, what I actually want is:

```
((foo bar baz)|              -> ((foo bar baz))| ;; re-indent the expression
​   )
```

**Comment by Fuco1** [comment]
There is a `ZERO WIDTH SPACE` character before the closing paren, that's why it is not working.  While I'm not sure why I think that is such a rare edge-case it's not much worth investigating.  I can not reproduce it after I remove that character.

If you disagree and this is still an issue feel free to reopen.
