### ISSUE TITLE
Wrap overlays not highlighted

### ISSUE THREAD

**Issue by d125q** [Fuco1/smartparens#606]
As far as I understand, having a line such as
```
+ 1 2
```
Then selecting it and typing `(` should give me
```lisp
(+ 1 2)
```
which it does.  However, it is to my understanding that smartparens should highlight the `(` using `sp-wrap-overlay-opening-pair`, the `(` using `sp-wrap-overlay-closing-pair`, and the text in-between using `sp-wrap-overlay-face`, which it doesn't.  Am I missing something here?

**Comment by Fuco1** [comment]
Yes, you are missing something :P

Those faces are used for the "popup" menu when all available wrappings are shown.  That only happens with pairs longer than one character.  Try it in a latex buffer, start with `\`.

Where did you get your present information?  We should probably clarify the documentation or comment there.

As for `sp-wrap-overlay-face`, that probably isn't even used anymore, it was used with the tag feature which has been since removed.

**Comment by d125q** [comment]
Thank you, @Fuco1.  I simply misunderstood the code.  It would help if the `defface` statements provided better documentation though.

`sp-wrap-overlay-face` _does_ seem to be used to highlight the wrapped pairs in the "popup" menu, though.

**Comment by Fuco1** [comment]
Okey, thanks for the feedback. I'll improve the docstring.
