### ISSUE TITLE
the beginning and ending of paren sexp

### ISSUE THREAD

**Issue by ambjlon** [Fuco1/smartparens#607]
The beginning of paren sexp is not "(", but is the next char of "(". 
The ending of the paren sexp is not ")", but is the next char of ")".
Why is  Smartparens designed in this way?

**Comment by Fuco1** [comment]
It isn't designed that way, you must be using some other package like evil which makes it seem weird.

In emacs point is between characters.  Beginning is between the previous character and the `(` and end is between `)` and the next character.  That is consistent with all of emacs, including the build in syntax parsers.

**Comment by ambjlon** [comment]
I am not using evil packages. ...
For sexp: {print 'hello!' }, when my cursor is on "{", sp-end-of-sexp cannot take  the cursor to  "}"
However, when my cursor is on the next  char of "{", that is "p", sp-end-of-sexp can take the cursor to "}".

**Comment by Fuco1** [comment]
Well that's by design and consistent with what I said.  When your cursor is *on* the `(` you are not inside the sexp, which means you can't travel to the end.  Note also that `sp-end-of-sexp` goes to inner end, not the outer one.  use `sp-forward-sexp` to skip over the sexp.  When inside and you want to jump out, `sp-up-sexp`.
