### ISSUE TITLE
Insert parentheses in the middle of a word/variable name

### ISSUE THREAD

**Issue by 3rd3** [Fuco1/smartparens#646]
Hi, I often have the case in all kinds of programming languages that I retrospectively want to add some function and add parentheses around some expression like this:

    some(nested(function(application(expression))))

then I move the cursor where I want to add function `foo`

    some(nested(▊function(application(expression))))

I write `foo`:

    some(nested(foo▊function(application(expression))))

But then smartparens automatically adds a closing bracket once I open one:

    some(nested(foo(▊)function(application(expression))))

Would it generally make sense to not do that automatic `)`-insertion when the pointer is in the middle of a word? Can I somehow add this as an exception? Am I overlooking some function that accomplishes that (apart from passthrough via `C-q`)?

**Comment by Fuco1** [comment]
So as a result you would want to wrap the entire inner argument as an argument to foo?  Why is it not desirable to insert parens there if you are adding new function call?

You can achieve what you want by doing what the person did in this issue https://github.com/Fuco1/smartparens/issues/645 but I would like to understand the motivation.

I can't for example imagine a situation where your function would be called `foo(function`, even ignoring the fact that's not valid syntax pretty much anywhere.  And if we don't close, you will end up with badly formated code.

If your problem is that you want to move the newly inserted paren to the end of the expression, call `sp-slurp-sexp`, bound to `C-M-<right>` by default.

**Comment by 3rd3** [comment]
These are some good suggestions, thanks! I'll try to get used to slurping.
