### ISSUE TITLE
In php code, input quotation in some case will add a slash automatic

### ISSUE THREAD

**Issue by quanyufang** [Fuco1/smartparens#656]
for example, I write fllow code 
`echo ("this is" . "a test");`
then I move cursor to the last quoation , remove it add retype a quotation, will result like below
`echo ("this is" . "a test\");`

If there is any way out?

**Comment by Fuco1** [comment]
The easiest way is not to remove the closing quote.  `C-q "` also works.  `smartparens-strict-mode` is also helpful.

By deleting the quote you change the context from code to string.  To preserve the context, the quote is escaped.

**Comment by quanyufang** [comment]
Thanks for your advisement. 'C-q' is what I need.

**Comment by Fuco1** [comment]
There was a setting `sp-autoinsert-quote-if-followed-by-closing-pair` which would make sure inserting quote before another closing delimiter would close the string instead of continue (because it would break the outer structure).  It doesn't work anymore but I'm working on it :)

(so in case you have `echo (....)` and you open a quote inside the parens, it won't allow you to break that pairing)
