### ISSUE TITLE
Define a local pair and override it ?

### ISSUE THREAD

**Issue by Yevgnen** [Fuco1/smartparens#680]
Hi, 

I read the wiki page of Permissions and it tells that one can override the global pair by `sp-local-pair`. But is it possible to define a local pair and override it?

For example, I want to define the `//` pair in org mode, with the minimal config
```
(package-initialize)
(require 'org)
(require 'smartparens)
(smartparens-strict-mode t)
(show-smartparens-global-mode t)
(add-hook 'org-mode-hook #'smartparens-mode)

(sp-with-modes 'org-mode
  (sp-local-pair "\\|" "\\|")
  (sp-local-pair "/" "/" :post-handlers '(("[d1]" "SPC")))
  (sp-local-pair "/" nil :unless '(sp-point-after-word-p) :actions '(insert wrap autoskip)))
```

Q1: Is it normal to do this ? 

If yes, I have a second question, that is
Q2: Is
```
:actions '(insert wrap autoskip) == :actions '(:rem navigate)
``` 
?

 I've tired to use `:rem` but this would make variable `sp-local-pairs` in a org buffer lack of the definition of `//`.

Then I read the doc of `sp-local-pair`, it says 
```
If the pair is not defined globally, ACTIONS defaults to (wrap
insert) instead of (:add) (which inherits global settings)
```

This seems to imply that in a local definition `'(:rem navigate) == '(wrap insert)` ? But with the setting 
```
  (sp-local-pair "/" "/" :post-handlers '(("[d1]" "SPC")) :unless '(sp-point-after-word-p))
```
I can see the value of `sp-local-pairs` gives 
```
 (:open "/" :close "/" :actions
	(wrap insert autoskip navigate)    <----------------
	:when nil :unless
	(sp-point-after-word-p)
	:pre-handlers nil :post-handlers
	(("[d1]" "SPC")))
```

Finally, the third question Q3 is when the cursor is between `OPEN` and `CLOSE`, for example `/I/`, using `sp-backward-delete-char` to delete `OPEN`, the `CLOSE` is left there. Is this feature related to permission `navigate`? Since I read from wiki that 
```
navigate - Enable this pair for navigation/highlight and strictness checks.
```
I want to remove navigate because the single `/` will also be highlight with a wrong `/` pair far before `(point)` and the org faces help recognizing the content between the pair so want to remove the highlight. But removing it causes I can not delete `CLOSE`.

So now I'm really messed these things, and can not understand how to define a local pair with specified actions and permission. Any help will be appreciated ! Thanks !

**Comment by Fuco1** [comment]
Q1: Yes, you can define local pairs which are not defined globally.  But you *can not* (in the current system) define the pair twice as you do.  You need to pull all the keywords in a single call (this will change in the upcoming revision of the configuration DSL)

Q2: That seems like a possible bug.  To be sure spell the actions out manually.  If there is no global definition I'm not sure what would happen if you try to `:rem` something (I probably never thought about that possibility)

Q3: The permission system sucks... it is not fine grained enough and so permissions are sometimes reused for seemingly unrelated tasks.  I'm working on it.  In strict mode with navigate the pair is killed entirely, in nonstrict mode it should as well due to `sp-delete-pair` (check the docstring and related settings).

If you only have a lonely `/` it should get highlighted as "unmatched", never match with a remote `/`. This can be annoying but not that much I feel.  Can you maybe provide an example buffer where you have the problem?

**Comment by Yevgnen** [comment]
Thanks for you reply!

For, Q1, I've tried to pull all the keywords in a single call and it works like that in two calls, though it's not designed to use two calls in a local pair definition.

For Q2, I tried `:rem navigate` because of Q3 which highlight the wrong pair and it just a bit shorter than listing all the other actions in code, or more logically to only remove the `navigate` action.

For Q3, which get highlighted with a remote pair, here's and example with the above minimal config containing a `navigate` action

![sp](https://cloud.githubusercontent.com/assets/16749790/20648577/ee65eb92-b4e5-11e6-8d37-9a507a8848e8.gif)

In matlab mode, the matrix transpose `'`(single quote) also being highlighted with remote one, though it's not really that annoying.

**Comment by Fuco1** [comment]
Q3: Oh yes, that happens to me too... I just never see the markup characters because I hide them... so I never noticed.  That's a bug indeed.

In the new configuration system I'm working on the `:rem` and `:add` for lists will be removed because it is sometimes quite unobvious what should happen... so you will have to list the permissions out manually... but I found out that virtualy nobody ever uses the add/rem options so it's not a big loss (and it is a one-time annoyance to list the permissions).
