### ISSUE TITLE
smartparens painfully slow in string literals in large Python file

### ISSUE THREAD

**Issue by marienz** [Fuco1/smartparens#752]
## Expected behavior
smartparens does not noticably affect Emacs performance.

## Actual behavior
When editing a large Python (haven't tested other languages) file, Emacs pauses for multiple seconds while smartparens is active. I've mostly noticed this while moving around string literals.

## Steps to reproduce the problem
- Open a large Python file, like https://github.com/cython/cython/blob/master/Cython/Compiler/ExprNodes.py
- Turn on smartparens-mode and show-smartparens-mode
- Move point around across the string `'in'` on line 12222

Emacs hangs for about 2 seconds when moving point across the boundary of the string literal.

I tried to narrow the problem down a bit, and found:

- The profiler says most time is spent below `sp-get-stringlike-expression`, when `sp--find-next-stringlike-delimiter` calls `looking-back`. A single call to `sp-get-stringlike-expression` while point is after the starting quote of `'in'` is slow (>2s).
- The `(while (sp--find-next-stringlike-delimiter needle 'search-backward-regexp (car limit) skip-match-fn) (setq count (1+ count))))` loop runs 1651 or 1653 times, and it looks like that's where most of the time goes.
- Before that loop runs, point has been moved to immediately before or after the string point is in, so `(sp-point-in-string)` returns nil and `limit` is not set.

It looks like that loop counts delimiters, to figure out if we're before an even or odd number. It'd be nice to bound that search, but I don't know if that's possible.

If it can't be bounded, it can easily be made a lot faster by avoiding the use of `looking-back` in `sp--find-next-stringlike-delimiter`. Replacing that with `(char-equal (char-before) ?\\)` helps a lot (note I'm not sure that replacement is entirely correct, I don't speak elisp... it's probably wrong if there's a quote at the start of the buffer, at least).

`looking-back` is being used to check if we're right after a single backslash. But it's implemented as a regular expression match (in this case on `\(?:\\\)\=`) against the entire buffer before point. Presumably the regexp engine isn't smart enough to recognize this expression will only ever match starting one character before point, and is searching for backslashes from the start of the buffer. Doing that once would not be too noticeable, but doing it once for every string delimiter in the buffer before point kills performance.

Skimming the smartparens source, there are several more places that call `looking-back` (or `sp--looking-back`, which constructs a similar regexp) with a fixed string. Passing a suitable limit or replacing them with a simple substring match might speed up other parts of smartparens.

(It'd be nice if `looking-back` was faster, but since the function's documentation says to avoid it because it is slow, I wouldn't hold my breath for it being made faster...)

## Environment & version information

- `smartparens` version: 20170531.742 from MELPA
- Active major-mode: python-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 25.2.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.12) of 2017-04-23
- OS: Linux

**Comment by Fuco1** [comment]
Thanks for the detailed report.  The main problem here is about how `python-mode` works with strings.  Because it uses two delimiters and there are some hacky hacks in python (like the tripple strings and so) the mode does not use regular syntax class for string delimiters but something called "general string fence".  This also allows you such features as nesting `'` inside `"` without the font-locker (and emacs parser) going insane... you mark the outer ones as "string fences" and inner ones as punctuation.  This all happens dynamically during some parsing stage (I'm not really sure when but I'm afraid it might actually be font-lock doing this).

To accomodate such languages (it isn't just python) we have couple "performance" hacks inside smartparens.  One of those hacks, turns out, got out of hands :D

I have fixed it using narrowing which is a pretty sweet use-case. All usages of looking-back should be capped to 10 characters in smartparens, that's why we have the wrapper `sp--looking-back(-p)`.  However I will use some good points from your analysis and make it a separate commit to try to make these things faster in general.

**Comment by marienz** [comment]
Thanks, it's a lot faster now! Using the same file as testcase, the pauses went from 2 seconds to no longer noticeable.
