### ISSUE TITLE
How to reformat stray closing parens and prevent extra closing parens

### ISSUE THREAD

**Issue by mfiano** [Fuco1/smartparens#778]
2 problems I could not find the answer to while deciding if this package is right for me:

1) If I have say the following, where `_` is the point:

```
(((_

)   )
      )
```
In paredit, pressing `)` 3 times would result in `((()))_`. How do I replicate this behavior in strict-mode?

2) In strict-mode, how do I prevent extra closing parens from being inserted if I type `)` at the end of a pair?

**Comment by Fuco1** [comment]
1. Calling `sp-up-sexp` instead of `)` will jump out and also realign.  We might add a feature to do the same on `)` when it is configured to jump out (I personally always use `sp-up-sexp` because that's in my muscle-memory, in fact, I have `)` rebound to entirely different command because I never use it.  This is probably the reason why it isn't implemented yet)

2. That should not happen.  Make sure you have the latest version.  When you try to insert a closing delimiter without an opening one you should get a message

    We can not insert unbalanced closing delimiter in strict mode.

in the minibuffer.

**Comment by mfiano** [comment]
@Fuco1, This is not the case for me. If I type `())` The minibuffer says `Search failed. This means there is unmatched expression somewhere or we are at the beginning/end of the file.`

**Comment by mfiano** [comment]
With strict-mode enabled, and binding `)` to `sp-up-sexp`, this has the unfortunate but understandable side effect of not allowing *any* `)` characters to be inserted manually - particularly troublesome when creating double-quoted strings. Do you have a quick workaround for this?

**Comment by Fuco1** [comment]
You can use `C-q` to insert any key literally in emacs.  So `C-q )` will insert `)` in the buffer no matter what you bind to it.

It should be relatively simple to add the "cleanup" behaviour to the `)` in strict-mode.  Let's leave this issue open so I have a reminder.  Then you can just leave it be and it would work (hopefully).  In the meantime, the above should help.

**Comment by mfiano** [comment]
Ok, thank you for the quick reply.

**Comment by Fuco1** [comment]
So I finally got to this, turns out it is already implemented, I just need to pass an additional flag to the function.

It should be enabled by default for all lisp modes and you can customize the behaviour by tweaking `sp-navigate-reindent-after-up` (but shouldn't need to)

So after you pull the latest patch you shouldn't need to do anything and it will just work (provided you use strict mode), which means you can also unbind the `)` to be just the regular paren.

**Comment by mfiano** [comment]
Thanks. At first glance this seems to work great
