### ISSUE TITLE
Change in spacing with sp-forward-slurp-sexp w.r.t. space.

### ISSUE THREAD

**Issue by harold** [Fuco1/smartparens#781]
First, thanks for smartparens, I _love_ it. I've got so many wicked workflows going that I never could quite manage with paredit.

I recently upgraded from 1.9 to 1.10.1, not sure if this is related to that, but slurping is eliding a space that my muscle memory is somehow expecting, and I'm wondering if the following is intended. I really appreciate your time and consideration.

## Expected behavior
`(foo|)(bar)` :arrow_right: `sp-forward-slurp-sexp` :arrow_right: `(foo (bar))`

## Actual behavior
`(foo|)(bar)` :arrow_right: `sp-forward-slurp-sexp` :arrow_right: `(foo(bar))`

(no space after `foo` :neutral_face:)

## Environment & version information

- `smartparens` version: 1.10.1
- Active major-mode: Clojure
- Emacs version (`M-x emacs-version`): `GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-25 on lgw01-10, modified by Debian`

- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Vanilla
- OS: `Linux gibson 4.8.0-58-generic #63-Ubuntu SMP Mon Jun 26 17:08:21 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Fuco1** [comment]
Hey, first of all thanks for the kind words :blush: 

There were indeed some changes related to what you describe, in particular, we no longer insert a space in case the slurp will not make the operation irreversible.  Consider `(foo|)bar`, if we simply do `(foo|bar)` and then reverse we will end up with `(|)foobar` which is not the original, so we have to insert a space there before moving the closing paren.

In your case, because there are extra parens around the token we can safely revert the slurp with a barf and no space is inserted.

The main issue was that in almost all languages except lisp we had to add special hacks to remove the spaces because there the tokens were better distinguished (for example with dot chains in method calls or semicolons etc).

Having said all that I think we should maybe bring back the behaviour for lisps as a special addon because I agree very much it looks better with a space.  It seems I have something like that in my personal config because it behaves like you would expect :D Which means I just need to package it and publish it.

**Comment by harold** [comment]
Ha! That makes total sense, I hadn't thought of slurp and barf as inverses. The three-way interaction between that, language variations (I basically only use SP for lisps), and expectations from other environments makes for twisty landscape of behaviors to explore.

I think what you say makes sense; for lisps, eliding that space (while still syntactically valid ❗️) goes against most code/style conventions.

Looking forward to a future version with that packaged and published, then. Thanks again, and if I can be of service w.r.t. to this or anything else, let me know.

**Comment by harold** [comment]
Hello again. (: and congratulations on 1.11.0

Any thoughts on recovering the above functionality for lisps?

Thanks!

**Comment by Fuco1** [comment]
Huh, I actually thought this was fixed :O I agree that this does not look good at all.  I guess I will introduce some variable to override the behaviour and "just insert a space" even if it is not necessary.  Thanks for the reminder :)

**Comment by harold** [comment]
If this gets fixed for elisp will it also work in Clojure?

**Comment by Fuco1** [comment]
Yea, should work for all lisps, we have a variable which lists all "lisp-like" major modes, see `sp--lisp-modes`

**Comment by garlic0x1** [comment]
I am using this as my slurp method for lisps to solve this
```lisp
(defun sp-smart-slurp ()
  (interactive)
  (sp-forward-slurp-sexp)
  (skip-syntax-forward "w_")
  (when (sp-wants-space-after-p)
    (insert " ")))

(defun sp-wants-space-after-p ()
  (not (or (looking-at "\\s-")
	   (looking-at ")")
	   (looking-at "]")
	   (looking-at "}"))))
```

**Comment by Fuco1** [comment]
Thanks @garlic0x1, I added a similar handler to the built-in config so now this will work out of the box.

**Comment by harold** [comment]
Love to hear it.
