### ISSUE TITLE
Need show-paren-priority to to make the region face take priority

### ISSUE THREAD

**Issue by amosbird** [Fuco1/smartparens#801]
![image](https://user-images.githubusercontent.com/5085485/31848855-6e289c06-b5ff-11e7-8595-1421ea3ab337.png)

Currently smartparens uses hard coded 1000 as priority.

**Comment by Fuco1** [comment]
I'm not sure what the screenshot is demonstrating.  Is it that you don't want to see the pair highlight if it is inside a region?

I think that would be better fixed with a `use-region-p` check.  The overlay priorities overall are a bit of a kludge I feel

**Comment by amosbird** [comment]
Hi @Fuco1 . I'd like the highlight background face not overriding the region's facing while still has the foreground face (red).

**Comment by amosbird** [comment]
This can be workaround in show-paren-mode.

https://emacs.stackexchange.com/questions/17324/how-to-make-the-region-face-take-priority-over-the-show-paren-mode-face

**Comment by valff** [comment]
Is there a solution for the issue? Look at the screenshot:

![Screenshot from 2019-05-18 22-47-19](https://user-images.githubusercontent.com/12503689/57974326-264ff700-79bf-11e9-918f-3fe68918e990.png)

It is impossible to distinguish whether the closing pair belongs to the region or not. `show-paren-mode` can be fixed with `show-paren-priority`, and how to fix `show-smartparens-mode`?

**Comment by Fuco1** [comment]
I personally never run into this problem, as most of the time I select pairs with the sexp-navigation functions and then I know the closing pair is included.

I think we can add a similar solution as `show-paren-mode` but this is low priority enhancement for me.  Pull requests are very welcome though.
