### ISSUE TITLE
sp-backward-kill-word skips inappropriately in ESS

### ISSUE THREAD

**Issue by jabranham** [Fuco1/smartparens#813]
This bug was apparently introduced in this commit (e389877 * [Fix #699] Properly skip over regexp-based prefixes), as I don't experience the bug in the previous commit (a0d52e4 * Fix org asterisk skip function at bol)

## Expected behavior
In R-mode (from ESS) with `|` representing point:

```
mean(mtcars$mpg|)
```

Running sp-backward-kill-word should result in 

```
mean(mtcars$|)
```

## Actual behavior

```
mean(|$mpg)
```

## Steps to reproduce the problem
See above

## Environment & version information

- `smartparens` version:
- Active major-mode: ESS
- Emacs version (`M-x emacs-version`): 25.3.1
- OS: linux

**Comment by Fuco1** [comment]
Oh, this is quite beautiful bug :)

I've made a mistake to check for prefix on any delimiter, including the closing ones :D So since your point is at `)` and words are prefixes of `()` pair (so that you kill the function name with the pair when unwrapping) it picks up `msg` as "prefix" and skips over it.  If you move the point to be over `g` it properly kills `mg` up to the `$`.

This is an easy fix, but I can't imagine every finding out!  Good catch!

**Comment by jabranham** [comment]
Thanks!
