### ISSUE TITLE
false positive "mismatched sexp state"

### ISSUE THREAD

**Issue by fommil** [Fuco1/smartparens#816]
## Expected behavior

```
def productz[Z](f: Destringify ~> Id => Z): Destringify[Z] 
```

selecting from `f: ^Destringify  ~> Id^` and pressing `(` should select the region.

## Actual behavior

mismatched sexp state.

## Steps to reproduce the problem

This is my config

https://gitlab.com/fommil/dotfiles/blob/master/.emacs.d/init.el#L507-543

I'm running the latest unstable from melpa.

Wild guess: my `(sp-pair "<" ">" :wrap "C-<")` somehow adds `<` and `>` into a global list of things that need to match. Do I need to tell the `self-insert-hook` to use some restricted set of parens?

**Comment by Fuco1** [comment]
If that pair is not useful in `scala-mode` you can disable it there: `(sp-local-pair 'scala-mode "<" ">" :actions nil)` should do the trick.

If it is useful in s`scala-mode` then it would be best to add some configuration to ignore `~>` when in the context where it does not mean a pair.  There is similar config for rust.  We can do that in the SP default config so that everyone benefits.
