### ISSUE TITLE
sp-backward-delete-char does not delete region if region is active

### ISSUE THREAD

**Issue by jabranham** [Fuco1/smartparens#827]
## Expected behavior
In org mode or python-mode with a buffer containing:

```
# test comment
```

mark the whole buffer and hit backspace should delete everything

## Actual behavior

One character is deleted backward (from point)

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: current git checkout
- Emacs version (`M-x emacs-version`): 25.3
- OS: linux

**Comment by Fuco1** [comment]
This seems to happen to me somewhat randomly too.  Usually toggling `delete-selection-mode` fixes the problem.  Can you try that?

**Comment by jabranham** [comment]
Toggling delete-selection-mode fixed it. I now load smartparens after enabling delete-selection-mode and haven't experienced this issue again.

**Comment by Fuco1** [comment]
There were some changes to the handling of delsel features, I now use the "native" flags instead of custom advices.  It might be the case that I forgot to initialize something somewhere, or update a hook that would do that after loading delsel.  I'll keep this open to remind me to look into it.  But the workaround here is rather painless so I think it's not a huge priority.

Thanks for confirming that it works!
