### ISSUE TITLE
Autodelete pairs

### ISSUE THREAD

**Issue by xendk** [Fuco1/smartparens#829]
What I wanted was this:

```
empty($var);
```

When deleting any of the `(` or `)`, forward or backward, it would take out the matching one, regardless of whether I just inserted them or not. Basically an unwrap. But I never figured out a way to configure smartparens like this, so I ended up writing my own, ugly, but working hack. Works nicely, been using it for years.

Anything I've overlooked in smartparens configuration? Or is there a particular reason why this feature doesn't exist?

**Comment by Fuco1** [comment]
And the end result should be `empty` or `empty$var`?  There is `sp-unwrap-sexp` which will remove the pairs if called from before or inside or `sp-backward-unwrap-sexp` if called from outside and after the pair.

**Comment by Fuco1** [comment]
If you mean to just backspacing over the pair and having the other one removed, that does not exist except when the pair is empty (ie only whitespace between the delimiters), then it is removed.  Otherwise not.  Also does not work in strict mode, there you have to explicitly call unwrap or the sexp has to be completely empty (ie the delimiters are touching each other)

**Comment by xendk** [comment]
`empty$var;`

I was thinking of the latter. I have a poor memory for specialized commands so I prefer that Emacs just Do The Right Thing.

I'll look into using `sp-unwrap-sexp`/`sp-backward-unwrap-sexp` in my code rather than just deleting the matching char by hand. Probably going to ease things when I get around to looking at automatically reindenting the affected region on wrapping/unwrapping.

Is it a feature you'd consider including, if provided an implementation?

**Comment by Fuco1** [comment]
I personally would find it quite confusing if backspacing over a paren would remove the opening one, especially in lisp or code with long methods where the other end might not even be visible, or not easily visible.  There I prefer explicit function call to do the unwrapping.  With strict mode backspacing a closing delimiter simply skips over it into the sexp which is a very handy behaviour I think.

If you want to code something up to do what you wish I'm not opposed to a patch at all, but it would have to be configurable and off by default (or as another minor mode user could toggle) because to both the users of strict mode and non-users it might be quite unexpected behaviour.  Maybe there's a third group (well, there's you at least) of people who would find this useful, which would be a net benefit if we can also provide something for them, so yea, PR welcome!

**Comment by xendk** [comment]
> I personally would find it quite confusing

Yeah, I would take some getting used to after years of manual pair management, but it's become quite natural to me. And in my editing style, when I delete one end of a pair, I mostly want to delete the other too. 

> PR welcome

OK, I'll see when I get the time to clean up my code.
