### ISSUE TITLE
smartparens seems not not work with ESS

### ISSUE THREAD

**Issue by TotalNewbi** [Fuco1/smartparens#83]
I have installed ESS (emacs speaks statistics) to use Emacs for R programming. smartparens works like a charm (thanks for sharing that code!) in a buffer where a R script file (ESS major mode) is open, but it does not work in the R console buffer (with iEss major mode). Is there any way to activate it here as well?

Cheers
Newbi

P.S. The relevant part of my .emacs is:

;; global
(require 'smartparens-config)
(smartparens-global-mode t)

;; highlights matching pairs
(show-smartparens-global-mode t)

**Comment by andrew-christianson** [comment]
For reference, this appears to be a configuration problem on Fuco's part.  [This](http://emacs.1067599.n5.nabble.com/using-smatparens-mode-in-iESS-R-buffer-td285003.html) thread indicates that the correct hook to use is `ess-R-post-run-hook` rather than the `inferior-ess-mode-hook`.  I can confirm that adding smartparens-mode to the former has the expected effect in inferior processes, while adding to the latter does not.

**Comment by Fuco1** [comment]
Thanks for sharing :) Incidentally, I might get into some R prototyping soon so this is welcomed indeed.

**Comment by andrew-christianson** [comment]
Quite welcome.  This thread is also the the first google hit for 'ess smartparen', so per [xkcd](http://xkcd.com/979/)...
