### ISSUE TITLE
sp-kill-hybrid-sexp doesn't recognize "?" and "!" on Ruby methods/symbols

### ISSUE THREAD

**Issue by wendelscardua** [Fuco1/smartparens#851]
(On my examples below, `|` is the cursor position)

## Expected behavior

Before `sp-kill-hybrid-sexp`:
```
|foo = 2.even?
bar = 2.odd?

```
After:
```
|
bar = 2.odd?
```

## Actual behavior

Before `sp-kill-hybrid-sexp`:
```
|foo = 2.even?
bar = 2.odd?
```
After:
```
|?
bar = 2.odd?
```

## Environment & version information

- `smartparens` version: 20180118.735
- Active major-mode: ruby-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Vanilla
- OS: gnu/linux

**Comment by Fuco1** [comment]
Huh.  This is odd because the `?` character is classified as a symbol and so should be part of the `even`.  Definitely a bug :)

**Comment by Fuco1** [comment]
Turns out Emacs sometimes places text properties on characters in the buffer to change their syntax.  This is what happened here, the `?` is by default punctuation but in the case where it's a suffix of a word it becomes a symbol.  Smartparens was until now ignoring the buffer text property.  This was causing this issue and a host of other subtle bugs that were really hard to discover.

Thank you for the report and sorry it took me 6 years to fix the issue.

From the manual:

> This function returns the raw syntax descriptor for the character in the buffer after position pos, **taking account of syntax properties** as well as the syntax table.
