### ISSUE TITLE
sp-forward-slurp-sexp problems in c-mode

### ISSUE THREAD

**Issue by bymoz089** [Fuco1/smartparens#855]
## Steps to reproduce the problem
Do a sp-forward-slurp-sexp in c-mode with cursor at `|`:
`(|)!foobar`

## Expected behavior
`(!foobar)`

## Actual behavior
`(foobar)!`

## Reproducibility:
always

## Notes
Similar effects happen with backward-slurp and several other characters (instead of `!`) in c-mode.

## Environment & version information
Calling `M-x sp-describe-system` gives no results.

- `smartparens` version: current MELPA: smartparens-20180204.844
- Active major-mode: c-mode
- Emacs version (`M-x emacs-version`): Emacs 24.5.1
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Vanilla
- OS: Linux

**Comment by bymoz089** [comment]
Another case, same problem, same setup:
"|"%s

## Expected behavior:
"%s"

## Actual behavior:
"s"%

**Comment by Fuco1** [comment]
Thanks for the report.  I've managed to reproduce this.  I think the problem is that the `!` is treated as punctuation which we want to move along with the braces (think of `;` for example).  However, `!` actually logically serves as a "prefix" in C languages so the Emacs's built-in syntax class does not quite match what we expect here.

With no definitions smartparens defaults to whatever the major mode provides so that's the issue here.  We'll have to provide our own declaration of the syntax for the purpose of this check.  This is a recurring problem and I think I'll have to come up with some more general solution than the usual hacks we employ.

**Comment by amosbird** [comment]
Is there a way to disable the punctuation moving behavior ?

**Comment by larebsyed** [comment]
Similar behaviour with "."
