### ISSUE TITLE
Support pp-eval-expression

### ISSUE THREAD

**Issue by aaronjensen** [Fuco1/smartparens#857]
## Expected behavior

It'd be great if `pp-eval-expression` supported smartparens similar to `eval-expression`. I don't know why it doesn't, but it doesn't seem to.

## Actual behavior

It doesn't support it, `(` inserts only `(`

## Steps to reproduce the problem

`M-x pp-eval-expression`

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: 20180204.844
- Active major-mode: help-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 26.0.91 (build 1, x86_64-apple-darwin17.3.0, NS appkit-1561.20 Version 10.13.2 (Build 17C205)) of 2018-01-13
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Spacemacs
- OS: darwin

**Comment by Fuco1** [comment]
I don't know why it is enabled in `eval-expression` :D because we have `minibuffer-inactive-mode` as an ignored mode in `sp-ignore-modes-list`.

What I have in my setup is

    (add-hook 'minibuffer-setup-hook 'turn-on-smartparens-strict-mode)

I'm actually using `eldoc-eval-expression` and it works with that as well as `pp-eval-expression`.

I think we decided to add it to ignored modes list because minibuffer is used for so many things that sometimes it's hard to say if we want to support it or not.  I think I don't care so I enabled it for myself (this was according to blame in 2014 so yea, I have no idea anymore :D)

**Comment by aaronjensen** [comment]
ahhh, thank you for the pointer. Spacemacs does this:

```
(defun spacemacs//conditionally-enable-smartparens-mode ()
  "Enable `smartparens-mode' in the minibuffer, during `eval-expression'."
  (if (eq this-command 'eval-expression)
      (smartparens-mode)))
```

So I can just adjust that if I want to.

Related, I was just introduced to `eldoc-eval` by the `doom` project. Most of this functionality appears to be built in to `eldoc` now, so why is `eldoc-eval` still used by some? The only thing I could figure out is that `eldoc` just prepends to the modeline right now, but `eldoc-eval` allows you to entirely replace the modeline or otherwise format it to your liking during an eldoc tooltip.

**Comment by Fuco1** [comment]
I use it because I've always used it, maybe it's not necessary anymore :D I'll have a look.

**Comment by aaronjensen** [comment]
Ah, makes sense. I'd be curious to know what you figure out. Cheers!
