### ISSUE TITLE
Bad detection of parentheses pairs in OCaml when surrounding comment

### ISSUE THREAD

**Issue by Khady** [Fuco1/smartparens#884]
I was trying smartparens with ocaml and I faced a problem which I think comes from bad detection of comment/doc. I get messages telling me there is an unmatched expression in my file.

The issue can be reproduced with this snippet.

```ocaml
let test = Some ( 1 + 2 (* this is a comment *) )
```

## Expected behavior

smartparens should be able to detect the matching parentheses properly.

## Actual behavior + Steps to reproduce the problem

The behavior depends on the position of the cursor. In both examples, I get a message in the minibuffer. With `<|>` being the cursor:

```ocaml
let test = Some ( 1 + 2 (* this is a comment *) )<|>
```

> Ignored: opening or closing pair is inside a string or comment and matching pair is outside (or vice versa).

```ocaml
let test = Some <|>( 1 + 2 (* this is a comment *) )
```

> Search failed: there is an unmatched expression somewhere or we are at the beginning/end of file. 

The problem doesn't seem to be present if there is a comment around parentheses containing another comment.

```ocaml
let test = Some 1 (* ( 1 + 2 (* *) ) *)
```

There is another strange behavior. I don't know if it is a bug or expected. But it is strange and also related to comments.

```ocaml
type t = {
  s: string;<|>
  d: int;
}
(* some documentation *)
```

In this case I call the command `sp-forward-slurp-sexp`. And I get a message `Wrong type argument: number-or-marker-p, nil`. Same message with `sp-slurp-hybrid-sexp`.

## Environment & version information

- `smartparens` version: 20180430.220
- Active `major-mode`: `tuareg-mode`
- Smartparens strict mode: t
- Emacs version (`M-x emacs-version`): GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian
- Starterkit/Distribution: Vanilla
- OS: gnu/linux

I am new to smartparens or anything like it, so please excuse the bad terminology or possible missing details.

**Comment by Fuco1** [comment]
I would expect that the opening `(` is not marked syntactically as comment or there is some other sorcery (like per-point overrides of syntax tables, python uses that) and we don't handle it properly.

It's definitely a bug.

**Comment by Fuco1** [comment]
Ok, this is amazing catch.

So the problem is that the closing `)` which is at the end of line (outside the comment) is marked as "possible 2nd character of a sequence closing a nested comment".  So what we do is we go back two characters and if we are in a comment then we say "right, this closes a comment and two chars before it there's a comment syntax running, which must mean we are in a comment".

So this is just a coincidence because two chars before the closing paren there is in fact a comment.  If you add one extra space in front of it things work.

The same bug also happens for example in C where

```c
float foo = 1 /* asdasd */ / 2
```

with point on the division symbol will report that the context there is being inside a comment (call `(sp-point-in-comment)` to check that).  Only in C it's not a problem because `/` is not a pair.

This is still a bug and needs to be fixed, but the cause is somewhere else and it's pretty funny how things turn out sometimes.
