### ISSUE TITLE
C-g dismisses Smartparens overlay before Company menu

### ISSUE THREAD

**Issue by raxod502** [Fuco1/smartparens#889]
## Expected behavior

When I open a pair, then trigger a Company menu, pressing C-g should dismiss the Company menu. Pressing C-g a second time should cancel the pair overlay.

## Actual behavior

The first C-g cancels the pair overlay, and the second C-g dismisses the Company menu. This feels weird. It is especially weird if I have disabled pair overlay highlighting, because then the first C-g is just a no-op.

## Steps to reproduce the problem

1. Start from `emacs -Q`.
2. Make packages `smartparens`, `company` available.
3. Run `M-x smartparens-mode`.
4. Run `M-x company-mode`.
5. Type `(find-`.
6. Wait for the Company menu to appear.
7. Press `C-g` twice and observe the results.

## Environment & version information

- `smartparens` version: 40f13c360544bbaa96f7ce5941429e8d55d92bb9
- `company` version: 779662f9e994c351002107a18f99cd06e00ed6c1
- Active major-mode: `lisp-interaction-mode`
- Emacs version (`M-x emacs-version`): 26.1
- OS: macOS 10.11.6

**Comment by Fuco1** [comment]
Oh yea, the overlay is still there only the highlight is not set.  So its local keymap is still active.

Emacs orders the overlays based on something called a "priority" which I suppose everyone uses with their own set of standards, so I might have a scale from 1 to 1000 and company from 1 to 100... in which case the smartparens overlay "wins" and the binding is looked up there.

I think I can change it so that if you disable the highlight it would also disable the keybinding.  The overlay still has to be there becase of some technical reasons (it is used for tracking state).

**Comment by raxod502** [comment]
How about https://github.com/Fuco1/smartparens/pull/890? (But the problem with Smartparens getting precedence over Company is still to be fixed.)

**Comment by raxod502** [comment]
It looks like Company's overlay has a priority of 1, while Smartparens' has a priority of 99. So either Company's has to be increased, or Smartparens' has to be decreased, if we want the behavior I outlined above.

**Comment by Fuco1** [comment]
I don't think we should mess with the priorities, that's pretty fragile system.  I don't understand your patch at #890 never having used the menu system.  Does this always bind the key but only executes the action conditionally?  In which case this still won't propagate the event to the company overlay right?

What I was thinking about was not adding the keymap to the overlay at all as I think `C-g` is now the only binding there so that shouldn't break anything really.

**Comment by raxod502** [comment]
No, #890 is a conditional binding. If the `:filter` returns nil, then the event propagates to the next available binding. [This is how `bind-key` implements conditional binding, for example.](https://github.com/jwiegley/use-package/blob/d3ace722ea890f9e99054af4487eff65c4e36243/bind-key.el#L187-L189)

I also don't object to not binding `C-g` ever; it doesn't affect me since I don't use the overlay highlighting.

**Comment by Fuco1** [comment]
Ok, so in that case this solves the issue here, does it not?

**Comment by raxod502** [comment]
#890 does not solve the problem I mentioned at the beginning of this thread. It does make the behavior less confusing when highlighting is disabled, though. If you simply didn't bind `C-g` ever, then it would solve the issue entirely.

**Comment by Fuco1** [comment]
Can we make the conditional filter somehow aware of company and not trigger if there is a company popup active?  Would that work?

**Comment by raxod502** [comment]
Sure, that works. I pushed a commit to that effect.

When highlighting is disabled, `sp-remove-active-pair-overlay` doesn't have any effect, right? If it does have an effect, we should remove my first change to unbind C-g when highlighting is disabled, and just unbind it when Company is active.

**Comment by Fuco1** [comment]
Some things behave differently if there is an "active overlay".  This means that you type a pair and then keep typing forward only.  If you hit the closing pair this will not be inserted but skipped.  There's a lot of ways this can be configured but some of them depend on the overlay (which is removed on backward motion).  In a way the overlay is there to also track some internal state.

In principle I think it shouldn't matter much.

**Comment by raxod502** [comment]
OK, but in the interest of making the behavior as unsurprising as possible, I've reverted my first commit, so that `C-g` always works, but defers to Company first if the popup is active.

**Comment by raxod502** [comment]
I think it's a solid improvement and further changes can be done separately. Thanks for the advice!
